company/urls.py
from django.conf.urls import url
from . import views
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(_(r'^createaccount/$'), views.createaccount, name='create_account'),
    url(_(r'^quotations/$'), views.quotations, name='quotations'),
    url(_(r'^quotation/create/$'), views.quotation_create, name='quotation_create'),
    url(_(r'^quotation/(?P<pk>[0-9]+)/proposals/$'), views.quotation_proposals, name='quotation_proposals'),
]

lawyer/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [
    url(_(r'^createaccount/$'), views.createaccount, name='create_account'),
    url(_(r'^proposals/$'), views.proposals, name='proposals'),
]

seudireito/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext_lazy as _

from seudireito import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(_(r'^login/$'), auth_views.login, name='login'),
    url(_(r'^logout/$'), auth_views.logout, name='logout'),
    url(r'', include('website.urls', namespace='website')),
    url(_(r'^lawyer/'), include('lawyer.urls', namespace='lawyer')),
    url(_(r'^company/'), include('company.urls', namespace='company')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(_(r'^quotations/$'), views.quotations, name='quotations'),
    url(_(r'^quotation/(?P<pk>[0-9]+)/$'), views.quotation, name='quotation'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from decimal import Decimal

from lawyer.models import Lawyer, Proposal
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, reverse, HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _

from company.models import Quotation
from utils.decorators import user_lawyer_required
from utils.paginator import listing


def index(request):
    ctx = {
        'total_lawyers': Lawyer.objects.all().count(),
        'quotations': Quotation.objects.filter(state='created').order_by('-created_date')[:4],
    }
    return render(
        request,
        'website/index.html',
        ctx
    )


def quotations(request):
    ctx = {
        'quotations': listing(request, Quotation.objects.filter(state='created'), 12),
        'title': _('Quotations')
    }
    return render(
        request,
        'website/quotations.html',
        ctx
    )


def quotation(request, pk):
    o_quotation = get_object_or_404(Quotation, pk=pk)
    try:
        # get logged lawyer
        lawyer = request.user.lawyer
        # get lawyer proposal or false
        lawyer_proposal = Proposal.objects.get(quotation=o_quotation, lawyer=lawyer)
    except Exception:
        lawyer_proposal = False
    if request.method == 'POST':
        proposal_value = Decimal(request.POST.get('proposal_value'))
        if proposal_value > 0:
            Proposal.objects.create(
                quotation=o_quotation,
                lawyer=lawyer,
                price=proposal_value
            )
            messages.success(request, _('Thanks for send your proposal.'))
            return HttpResponseRedirect(
                reverse('website:quotation', kwargs={'pk': o_quotation.pk})
            )
        else:
            messages.error(request, _('Invalid value.'))
    ctx = {
        'quotation': o_quotation,
        'lawyer_proposal': lawyer_proposal,
        'title': _('Quotation')
    }
    return render(
        request,
        'website/quotation.html',
        ctx
    )

website/templates/website/includes/block-header.html
<div class="page-header sm">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-header-wrapper">
                    <h5 class="title">{{ title }}</h5>
                </div>
            </div>
        </div>
    </div>
</div>

website/templates/website/includes/footer.html
{% load static %}
<footer id="footer" class="footer-1">
	<!-- Footer Copyright -->
	<div class="footer-copyright">
		<div class="container">
			<div class="row">
				<!-- Copy Right Logo -->
				<div class="col-md-2 text-center">
					<a href="{% url 'website:index' %}">
						<img src="{% static 'website/images/default/logo-footer.png' %}" width="211" height="40" class="img-responsive" alt="Universh Education HTML5 Website Template">
					</a>
				</div>
			</div>
		</div>
	</div>
</footer>

website/templates/website/includes/header.html
{% load static i18n %}
<header id="header" class="default-header colored flat-menu">
    <div class="header-top">
        <div class="container">
            <nav>
                <ul class="nav nav-pills nav-top">
                    <li class="phone">
                        <span><i class="fa fa-envelope"></i>christian.douglas.alcantara@gmail.com</span>
                    </li>
                    <li class="phone">
                        <span><i class="fa fa-phone"></i>(31)9.9550-4357</span>
                    </li>
                </ul>
            </nav>
            <div class="search">
                <form id="formSetLanguage" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    <input name="next" type="hidden" value="{{ redirect_to }}"/>
                    <input name="language" type="hidden" value="{{ LANGUAGE_CODE }}"/>
                    <select class="selectpicker" data-width="fit" data-style="btn btn-primary btn-sm" id="selectLanguage">
                        {% for language in languages %}
                            <option {% if language.code == LANGUAGE_CODE %}selected{% endif %}
                                    data-content='<i class="flag-icon flag-icon-{{ language.code }}"></i> <span style="color: black;" >{{ language.name_local }}</span>'
                                    name="sel_language"
                                    value="{{ language.code }}">{{ language.name_local }}
                            </option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="logo">
            <a href="{% url 'website:index' %}">
                <img alt="Universh" width="211" height="40" data-sticky-width="150" data-sticky-height="28"
                     src="{% static 'website/images/default/logo.png' %}">
            </a>
        </div>
        <button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
        </button>
    </div>
    {% include 'website/includes/navbar.html' %}
</header>

website/templates/website/includes/javascript.html
{% load static %}
<!-- library -->
<script src="{% static 'website/js/lib/jquery.js' %}"></script>
<script src="{% static 'website/js/lib/bootstrap.min.js' %}"></script>
<script src="{% static 'website/js/lib/bootstrapValidator.min.js' %}"></script>
<script src="{% static 'website/js/lib/jquery.appear.js' %}"></script>
<script src="{% static 'website/js/lib/jquery.easing.min.js' %}"></script>
<script src="{% static 'website/js/lib/owl.carousel.min.js' %}"></script>
<script src="{% static 'website/js/lib/countdown.js' %}"></script>
<script src="{% static 'website/js/lib/counter.js' %}"></script>
<script src="{% static 'website/js/lib/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'website/js/lib/jquery.easypiechart.min.js' %}"></script>
<script src="{% static 'website/js/lib/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'website/js/lib/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'website/js/lib/jquery.stellar.min.js' %}"></script>
<script src="{% static 'website/js/lib/menu.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<!-- Revolution Js -->
<script src="{% static 'website/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'website/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'website/js/lib/theme-rs.js' %}"></script>

<script src="{% static 'website/js/lib/modernizr.js' %}"></script>
<!-- Theme Base, Components and Settings -->
<script src="{% static 'website/js/theme.js' %}"></script>

<!-- Theme Custom -->
<script src="{% static 'website/js/custom.js' %}"></script>

{% if messages %}
    <script>
    {% for message in messages %}
    toastr.{{ message.tags }}("{{ message }}", "{{ message.tags }}", {
        "timeOut": "0",
        "extendedTImeout": "0",
        "closeButton": true,
        "newestOnTop": true
    });
    {% endfor %}
    </script>
{% endif %}

website/templates/website/includes/navbar.html
{% load i18n %}
<div class="navbar-collapse nav-main-collapse collapse">
		<div class="container">
			<nav class="nav-main mega-menu">
				<ul class="nav nav-pills nav-main" id="mainMenu">
                    <li>
                        <a class="dropdown-toggle" href="{% url 'website:quotations' %}">
                            {% trans 'Quotations' %}
                        </a>
                    </li>

                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#">
                                <i class="fa fa-user"></i> {{ user.get_full_name }}
                                <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.lawyer %}
                                    <li><a href="{% url 'lawyer:proposals' %}">{% trans 'Your proposal' %}<span class="tip green">{{ user.lawyer.proposals.all.count }}</span></a></li>
                                {% elif user.company %}
                                    <li><a href="{% url 'company:quotations' %}">{% trans 'Your quotations' %}<span class="tip green">{{ user.company.quotations.all.count }}</span></a></li>
                                    <li><a href="{% url 'company:quotation_create' %}">{% trans 'Create quotation' %}</a></li>
                                {% endif %}
                                <li><a href="{% url 'logout' %}">{% trans 'Logout' %}</a></li>
                            </ul>
                        </li>

                    {% else %}
                        <li>
                            <a class="dropdown-toggle" href="{% url 'login' %}">
                                {% trans 'Login' %}
                                <i class="fa fa-user"></i>
                            </a>
                        </li>
                    {% endif %}
				</ul>
			</nav>
		</div>
	</div>

website/templates/website/includes/slide.html
{% load static i18n %}
<div class="rs-container light rev_slider_wrapper">
		<div id="revolutionSlider" class="slider rev_slider" data-plugin-revolution-slider data-plugin-options='{"delay": 9000, "gridwidth": 1170, "gridheight": 500, "navigation": { "arrows": { "enable": false } }}'}'>
			<ul>
				<li data-transition="fade" class="typo-dark heavy">
					<img src="{% static 'website/images/banner/services.jpg' %}"
						alt=""
						data-bgposition="center center"
						data-bgfit="cover"
						data-bgrepeat="no-repeat"
						class="rev-slidebg">

					<div class="tp-caption sm-text" style="color: white; font-weight: 300"
						data-x="right" data-hoffset="30"
						data-y="135"
						data-start="600"
						data-transform_in="y:[-300%];opacity:0;s:500;">{% blocktrans %}More than {{ total_lawyers }} independent professionals are available to work on what you need{% endblocktrans %}</div>

					<div class="tp-caption big-text" style="color: white; font-weight: 300"
						data-x="right" data-hoffset="30"
						data-y="center" data-voffset="-30"
						data-start="1500"
						data-whitespace="nowrap"
						data-transform_in="y:[100%];s:500;"
						data-transform_out="opacity:0;s:500;"
						data-mask_in="x:0px;y:0px;">{% trans 'Hire the best lawyers in the world' %}</div>

					<div class="tp-caption sm-text"
						data-x="right" data-hoffset="260"
						data-y="285"
						data-start="2000"
						data-transform_in="y:[100%];opacity:0;s:500;">
                        <a href="{% url 'company:create_account' %}" class="btn btn-success">{% trans 'Request a professional' %}</a></div>

					<div class="tp-caption sm-text"
						data-x="right" data-hoffset="30"
						data-y="285"
						data-start="2000"
						data-transform_in="y:[100%];opacity:0;s:500;">
                        <a href="{% url 'lawyer:create_account' %}" class="btn btn-primary">{% trans 'Create lawyer account' %}</a></div>
				</li>
			</ul>
		</div>
	</div>

website/templates/website/includes/style.html
{% load static %}
<!-- Web Fonts  -->
<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
      rel='stylesheet' type='text/css'>

<!-- Lib CSS -->
<link rel="stylesheet" href="{% static 'website/css/lib/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/univershicon.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/prettyPhoto.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/menu.css' %}">
<link rel="stylesheet" href="{% static 'website/css/lib/timeline.css' %}">
<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
<!-- Revolution CSS -->
<link rel="stylesheet" href="{% static 'website/revolution/css/settings.css' %}">
<link rel="stylesheet" href="{% static 'website/revolution/css/layers.css' %}">
<link rel="stylesheet" href="{% static 'website/revolution/css/navigation.css' %}">

<!-- Theme CSS -->
<link rel="stylesheet" href="{% static 'website/css/theme.css' %}">
<link rel="stylesheet" href="{% static 'website/css/theme-responsive.css' %}">

<!--[if IE]>
<link rel="stylesheet" href="css/ie.css">
<![endif]-->

<!-- Skins CSS -->
<link rel="stylesheet" href="{% static 'website/css/skins/default.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
<link rel="stylesheet" href="{% static 'website/css/flags.css' %}">

<!-- Theme Custom CSS -->
<link rel="stylesheet" href="{% static 'website/css/custom.css' %}">