company/urls.py
from django.conf.urls import url
from . import views
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(_(r'^createaccount/$'), views.createaccount, name='create_account'),
    url(_(r'^quotations/$'), views.quotations, name='quotations'),
    url(_(r'^quotation/create/$'), views.quotation_create, name='quotation_create'),
    url(_(r'^quotation/(?P<pk>[0-9]+)/proposals/$'), views.quotation_proposals, name='quotation_proposals'),
]

lawyer/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [
    url(_(r'^createaccount/$'), views.createaccount, name='create_account'),
    url(_(r'^proposals/$'), views.proposals, name='proposals'),
]

seudireito/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext_lazy as _

from seudireito import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(_(r'^login/$'), auth_views.login, name='login'),
    url(_(r'^logout/$'), auth_views.logout, name='logout'),
    url(r'', include('website.urls', namespace='website')),
    url(_(r'^lawyer/'), include('lawyer.urls', namespace='lawyer')),
    url(_(r'^company/'), include('company.urls', namespace='company')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class TypeOfCompany(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=120,
        unique=True
    )

    class Meta:
        verbose_name = _("Type of company")
        verbose_name_plural = _("Type of companies")

    def __str__(self):
        return self.name


class Company(models.Model):
    user = models.OneToOneField(
        verbose_name=_("User"),
        to=User,
        help_text=_("It is necessary to relate a user to the Company to access the system.")
    )
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=120
    )
    type_of_company = models.ForeignKey(
        verbose_name=_("Type of company"),
        to=TypeOfCompany,
        null=True,
        on_delete=models.SET_NULL
    )
    email = models.EmailField(
        verbose_name=_("Email"),
        unique=True
    )

    class Meta:
        verbose_name = _("Company")
        verbose_name_plural = _("Companies")

    def __str__(self):
        return self.name


class Quotation(models.Model):
    company = models.ForeignKey(
        verbose_name=_("Company"),
        to=Company,
        related_name='quotations'
    )
    title = models.CharField(
        verbose_name=_("Title"),
        max_length=150
    )
    description = models.TextField(
        verbose_name=_("Description")
    )
    state = models.CharField(
        verbose_name=_("State"),
        max_length=8,
        choices=[
            ('created', _("Created")),
            ('delegate', _("Delegate")),
            ('finished', _("Finished"))
        ],
        default='created'
    )
    created_date = models.DateTimeField(
        verbose_name=_("Created date"),
        auto_now_add=True,
        editable=False
    )
    delegated_to = models.OneToOneField(
        verbose_name="Delegated to",
        to='lawyer.Proposal',
        blank=True,
        null=True,
        related_name="delegateds"
    )

    class Meta:
        verbose_name = _("Quotation")
        verbose_name_plural = _("Quotations")
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    @property
    def state_color(self):
        colors = {
            'created': 'warning',
            'delegate': 'info',
            'finished': 'success'
        }
        return colors.get(self.state, 'danger')

app/company/forms.py
from django import forms
from .models import Company, Quotation
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from app.lawyer.forms import LawyerCreationForm


class CompanyCreationForm(LawyerCreationForm):
    """
    A form that creates a company and related user with no privileges, from the given
    email and password.
    """

    class Meta:
        model = Company
        exclude = ['user']

    def save(self, commit=True):
        company = super(CompanyCreationForm, self).save(commit=False)
        if commit:
            user = User.objects.create_user(
                username=self.cleaned_data.get("email"),
                email=self.cleaned_data.get("email"),
                password=self.cleaned_data.get("password1"),
                first_name=self.cleaned_data.get("name")
            )
            company.user = user
            company.save()
        return company


class QuotationCreateForm(forms.ModelForm):
    """
    A form that create a quotations
    """
    class Meta:
        model = Quotation
        exclude = ['company', 'state', 'created_date']

company/forms.py
from django import forms
from django.contrib.auth.models import User

from lawyer.forms import LawyerCreationForm
from .models import Company, Quotation


class CompanyCreationForm(LawyerCreationForm):
    """
    A form that creates a company and related user with no privileges, from the given
    email and password.
    """

    class Meta:
        model = Company
        exclude = ['user']

    def save(self, commit=True):
        company = super(CompanyCreationForm, self).save(commit=False)
        if commit:
            user = User.objects.create_user(
                username=self.cleaned_data.get("email"),
                email=self.cleaned_data.get("email"),
                password=self.cleaned_data.get("password1"),
                first_name=self.cleaned_data.get("name")
            )
            company.user = user
            company.save()
        return company


class QuotationCreateForm(forms.ModelForm):
    """
    A form that create a quotations
    """
    class Meta:
        model = Quotation
        exclude = ['company', 'state', 'created_date']

app/company/views.py
from django.shortcuts import render, reverse, HttpResponseRedirect, get_object_or_404
from . models import Quotation
from app.lawyer.models import Proposal
from . forms import CompanyCreationForm, QuotationCreateForm
from django.utils.translation import ugettext_lazy as _
from utils.paginator import listing
from utils.decorators import user_company_required
from django.contrib import messages


def createaccount(request):
    if request.method == 'POST':
        form = CompanyCreationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = CompanyCreationForm()

    ctx = {
        'title': _("Create Account"),
        'form': form
    }
    return render(
        request,
        'company/create-account.html',
        ctx
    )


@user_company_required
def quotations(request):
    company = request.user.company
    ctx = {
        'title': _('Your quotations'),
        'quotations': listing(request, company.quotations.all(), 10)
    }
    return render(
        request,
        'company/quotations.html',
        ctx
    )


@user_company_required
def quotation_create(request):
    company = request.user.company
    if request.method == 'POST':
        form = QuotationCreateForm(request.POST)
        if form.is_valid():
            new_quotation = form.save(commit=False)
            new_quotation.company = company
            new_quotation.save()
            messages.success(request, _("Quotation '{}' created successfully").format(new_quotation.title))
            return HttpResponseRedirect(reverse('company:quotations'))
    else:
        form = QuotationCreateForm()

    ctx = {
        'title': _('Create quotation'),
        'form': form
    }
    return render(
        request,
        'company/quotation-create.html',
        ctx
    )


@user_company_required
def quotation_proposals(request, pk):
    o_quotation = get_object_or_404(Quotation, pk=pk)
    company = request.user.company

    if request.method == 'POST':
        action = request.POST.get('action')
        proposal_pk = request.POST.get('pk')
        proposal = Proposal.objects.get(pk=proposal_pk)
        if action == 'finish':
            o_quotation.state = 'finished'
            o_quotation.save()
            messages.success(request, _("Quotation '{}' finished").format(o_quotation))
        elif action == 'delegate':
            o_quotation.delegated_to = proposal
            o_quotation.state = 'delegate'
            o_quotation.save()
            messages.success(request, _("Proposal '{}' delegate").format(proposal))
        return HttpResponseRedirect(reverse('company:quotations'))

    ctx = {
        'title': _('Quotation proposals'),
        'quotation': o_quotation,
        'proposals': listing(request, o_quotation.proposals.all().order_by('price'))
    }
    return render(
        request,
        'company/quotation-proposal.html',
        ctx
    )

company/views.py
from django.contrib import messages
from django.shortcuts import render, reverse, HttpResponseRedirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from lawyer.models import Proposal
from utils.decorators import user_company_required
from utils.paginator import listing
from .forms import CompanyCreationForm, QuotationCreateForm
from .models import Quotation


def createaccount(request):
    if request.method == 'POST':
        form = CompanyCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _('Account created successfully'))
            return HttpResponseRedirect(reverse('login'))
    else:
        form = CompanyCreationForm()

    ctx = {
        'title': _("Create Account"),
        'form': form
    }
    return render(
        request,
        'company/create-account.html',
        ctx
    )


@user_company_required
def quotations(request):
    company = request.user.company
    ctx = {
        'title': _('Your quotations'),
        'quotations': listing(request, company.quotations.all(), 10)
    }
    return render(
        request,
        'company/quotations.html',
        ctx
    )


@user_company_required
def quotation_create(request):
    company = request.user.company
    if request.method == 'POST':
        form = QuotationCreateForm(request.POST)
        if form.is_valid():
            new_quotation = form.save(commit=False)
            new_quotation.company = company
            new_quotation.save()
            messages.success(request, _("Quotation '{}' created successfully").format(new_quotation.title))
            return HttpResponseRedirect(reverse('company:quotations'))
    else:
        form = QuotationCreateForm()

    ctx = {
        'title': _('Create quotation'),
        'form': form
    }
    return render(
        request,
        'company/quotation-create.html',
        ctx
    )


@user_company_required
def quotation_proposals(request, pk):
    o_quotation = get_object_or_404(Quotation, pk=pk)
    company = request.user.company

    if request.method == 'POST':
        action = request.POST.get('action')
        proposal_pk = request.POST.get('pk')
        proposal = Proposal.objects.get(pk=proposal_pk)
        if action == 'finish':
            o_quotation.state = 'finished'
            o_quotation.save()
            messages.success(request, _("Quotation '{}' finished").format(o_quotation))
        elif action == 'delegate':
            o_quotation.delegated_to = proposal
            o_quotation.state = 'delegate'
            o_quotation.save()
            messages.success(request, _("Proposal '{}' delegate").format(proposal))
        return HttpResponseRedirect(reverse('company:quotations'))

    ctx = {
        'title': _('Quotation proposals'),
        'quotation': o_quotation,
        'proposals': listing(request, o_quotation.proposals.all().order_by('price'))
    }
    return render(
        request,
        'company/quotation-proposal.html',
        ctx
    )

company/templates/company/base.html
{% extends 'website/base.html' %}

{% block header %}
    <div class="page-header sm">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-header-wrapper">
                        <h5 class="title">{{ title }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block main %}{% endblock %}

company/templates/company/create-account.html
{% extends 'website/base.html' %}
{% load static i18n bootstrap3 %}

{% block class_main %}
    class="main relative bg-img bg-cover overlay bg-color heavy"
    data-background="{% static 'website/images/banner/bg-21.jpg' %}" data-stellar-background-ratio="0.5"
{% endblock %}

{% block main %}
<div class="page-default typo-dark">
		<!-- Container -->
		<div class="container">
			<!-- Row -->
			<div class="row">
				<div class="col-md-offset-1 col-md-10 parent-has-overlay">
					<ul class="template-box box-login">
						<!-- Page Template Logo -->
						<li class="logo-wrap  text-center">
                            <h4 class="slogan">{% trans 'Create Account' %}</h4>
                            {% bootstrap_form_errors form error_types='all' %}
						</li><!-- Page Template Logo -->
						<!-- Page Template Content -->
						<li class="template-content text-left">
							<div class="contact-form">
								<!-- Form Begins -->
								<form name="bootstrap-form" method="post" action="{% url 'company:create_account' %}">
									{% csrf_token %}
                                    <div class="row">
                                        {% bootstrap_field form.type_of_company form_group_class="input-text form-group col-md-12" %}
                                    </div>
                                    <div class="row">
                                        {% bootstrap_field form.name form_group_class="input-text form-group col-md-6" %}
                                        {% bootstrap_field form.email form_group_class="input-text form-group col-md-6" %}
                                    </div>
                                    <div class="row">
                                        {% bootstrap_field form.password1 form_group_class="input-text form-group col-md-6" %}
                                        {% bootstrap_field form.password2 form_group_class="input-text form-group col-md-6" %}
                                    </div>
                                    <div class="row">
                                        <button class="btn btn-block btn-success" type="submit">{% trans 'Create my account' %}</button>
                                        <p class="text-center">or</p>
                                        <p class="text-center"><a href="{% url 'login' %}">{% trans 'click here to login' %}</a></p>

                                    </div>
								</form><!-- Form Ends -->
							</div>
						</li><!-- Page Template Content -->
					</ul>
				</div><!-- Column -->
			</div><!-- Row -->
		</div><!-- Container -->
	</div>
{% endblock %}

company/templates/company/quotation-create.html
{% extends 'company/base.html' %}
{% load i18n bootstrap3 %}

{% block main %}
    <section class="bg-grey pad-tb-30">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-3 col-md-6">
                    <form method="post" action="{% url 'company:quotation_create' %}">
                        {% csrf_token %}
                        <div class="row">
                            {% bootstrap_field form.title form_group_class="input-text form-group" %}
                        </div>
                        <div class="row">
                            {% bootstrap_field form.description form_group_class="input-text form-group" %}
                        </div>
                        <div class="row">
                            <a class="btn btn-danger" href="{% url 'company:quotations' %}">{% trans 'Cancel' %}</a>
                            <button class="btn btn-success" type="submit">{% trans 'Save' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

company/templates/company/quotation-proposal.html
{% extends 'company/base.html' %}
{% load static i18n bootstrap3 %}
{% block main %}
    <section class="pad-tb-30">
        <div class="container">
            <div class="row">
                <div class="panel-group accordion" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingTwo">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                {{ quotation }}
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <small class="label label-{{ quotation.state_color }}">{{ quotation.get_state_display }}</small>
                                <p>{{ quotation.description }}</p>
                                <p><i class="fa fa-calendar-o"></i> {{ quotation.created_date|date:"SHORT_DATE_FORMAT" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for proposal in proposals %}
                    <div class="col-sm-4">
                        <div class="content-box shadow {% if quotation.delegated_to == proposal %}bg-success{% else %}bg-white{% endif %}">
                            <div class="row">
                                <div class="col-sm-8">
                                    <h6 class="text-primary">
                                    {{ proposal }}
                                </h6>

                                </div>
                                <div class="col-sm-4">
                                    <div class="pull-right">
                                        {% if not quotation.delegated_to %}
                                            <form method="post"
                                                  action="{% url 'company:quotation_proposals' quotation.pk %}">{% csrf_token %}
                                                <input type="hidden" name="action" value="delegate">
                                                <input type="hidden" name="pk" value="{{ proposal.pk }}">
                                                <button type="submit"
                                                        class="btn btn-success btn-xs pull-right">{% trans 'Delegate' %}</button>
                                            </form>
                                        {% else %}
                                            {% if quotation.delegated_to == proposal and quotation.state == 'delegate' %}
                                                <form method="post"
                                                      action="{% url 'company:quotation_proposals' quotation.pk %}">{% csrf_token %}
                                                    <input type="hidden" name="action" value="finish">
                                                    <input type="hidden" name="pk" value="{{ proposal.pk }}">
                                                    <button type="submit"
                                                            class="btn btn-success btn-xs pull-right">{% trans 'Finish' %}</button>
                                                </form>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <table class="table margin-none">
                                <tbody>
                                    <tr>
                                        <th><strong>{% trans 'Lawyer' %}</strong></th>
                                        <td>{{ proposal.lawyer }}</td>
                                    </tr>
                                    <tr>
                                        <th><strong>{% trans 'Price' %}</strong></th>
                                        <td><strong><span class="amount text-danger">{{ proposal.price }}</span></strong></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <nav class="text-center">
                {% bootstrap_pagination proposals %}
            </nav>
        </div>
    </section>
{% endblock %}

company/templates/company/quotations.html
{% extends 'company/base.html' %}
{% load static i18n bootstrap3 %}
{% block main %}
    <section class="pad-tb-30">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-0 col-md-11">
					<table class="table table-hover">
						<thead>
							<tr>
								<th>{% trans 'Title' %}</th>
								<th>{% trans 'Description' %}</th>
								<th class="text-center">{% trans 'State' %}</th>
								<th class="text-center">{% trans 'Date' %}</th>
								<th class="text-center">{% trans 'Proposals' %}</th>
                                <th>{% trans 'Actions' %}</th>
							</tr>
						</thead>
						<tbody>
                            {% for quotation in quotations %}
							<tr>
								<th style="min-width: 150px" scope="row">{{ quotation }}</th>
								<td>{{ quotation.description }}</td>
								<td class="text-center">
                                    <span class="label label-{{ quotation.state_color }}">{{ quotation.get_state_display }}
                                        {% if quotation.delegated_to %}: {{ quotation.delegated_to }} {% endif %}
                                    </span>

                                </td>
								<td class="text-center">{{ quotation.created_date|date:"SHORT_DATE_FORMAT" }}</td>
								{% with quotation.proposals.all.count as total_proposals %}
                                <td class="text-center">
                                    <span class="badge badge-info">{{ total_proposals }}</span>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-sm {% if not total_proposals %}disabled{% endif %}" href="{% if not total_proposals %}javascript:void(0){% else %}{% url 'company:quotation_proposals' quotation.pk %}{% endif %}">{% trans 'View proposals' %}</a>
                                </td>
                                {% endwith %}
							</tr>
                        {% endfor %}
						</tbody>
					</table>
				</div>
            </div>
            <nav class="text-center">
                {% bootstrap_pagination quotations %}
            </nav>
        </div>
    </section>
{% endblock %}