lawyer/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [
    url(_(r'^createaccount/$'), views.createaccount, name='create_account'),
    url(_(r'^proposals/$'), views.proposals, name='proposals'),
]

seudireito/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext_lazy as _

from seudireito import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(_(r'^login/$'), auth_views.login, name='login'),
    url(_(r'^logout/$'), auth_views.logout, name='logout'),
    url(r'', include('website.urls', namespace='website')),
    url(_(r'^lawyer/'), include('lawyer.urls', namespace='lawyer')),
    url(_(r'^company/'), include('company.urls', namespace='company')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(_(r'^quotations/$'), views.quotations, name='quotations'),
    url(_(r'^quotation/(?P<pk>[0-9]+)/$'), views.quotation, name='quotation'),
]

company/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class TypeOfCompany(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=120,
        unique=True
    )

    class Meta:
        verbose_name = _("Type of company")
        verbose_name_plural = _("Type of companies")

    def __str__(self):
        return self.name


class Company(models.Model):
    user = models.OneToOneField(
        verbose_name=_("User"),
        to=User,
        help_text=_("It is necessary to relate a user to the Company to access the system.")
    )
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=120
    )
    type_of_company = models.ForeignKey(
        verbose_name=_("Type of company"),
        to=TypeOfCompany,
        null=True,
        on_delete=models.SET_NULL
    )
    email = models.EmailField(
        verbose_name=_("Email"),
        unique=True
    )

    class Meta:
        verbose_name = _("Company")
        verbose_name_plural = _("Companies")

    def __str__(self):
        return self.name


class Quotation(models.Model):
    company = models.ForeignKey(
        verbose_name=_("Company"),
        to=Company,
        related_name='quotations'
    )
    title = models.CharField(
        verbose_name=_("Title"),
        max_length=150
    )
    description = models.TextField(
        verbose_name=_("Description")
    )
    state = models.CharField(
        verbose_name=_("State"),
        max_length=8,
        choices=[
            ('created', _("Created")),
            ('delegate', _("Delegate")),
            ('finished', _("Finished"))
        ],
        default='created'
    )
    created_date = models.DateTimeField(
        verbose_name=_("Created date"),
        auto_now_add=True,
        editable=False
    )
    delegated_to = models.OneToOneField(
        verbose_name="Delegated to",
        to='lawyer.Proposal',
        blank=True,
        null=True,
        related_name="delegateds"
    )

    class Meta:
        verbose_name = _("Quotation")
        verbose_name_plural = _("Quotations")
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    @property
    def state_color(self):
        colors = {
            'created': 'warning',
            'delegate': 'info',
            'finished': 'success'
        }
        return colors.get(self.state, 'danger')

lawyer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from .validators import validate_phone_number, validate_cpf
import re


class Lawyer(models.Model):
    user = models.OneToOneField(
        verbose_name=_("User"),
        to=User,
        help_text=_("It is necessary to relate a user to the Lawyer to access the system.")
    )
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=120
    )
    phone_number = models.CharField(
        verbose_name=_("Phone"),
        max_length=13,
        validators=[validate_phone_number]
    )
    cpf = models.CharField(
        verbose_name=_("CPF"),
        max_length=14,
        unique=True,
        validators=[validate_cpf]
    )
    email = models.EmailField(
        verbose_name=_("Email"),
        unique=True
    )

    class Meta:
        verbose_name = _("Lawyer")
        verbose_name_plural = _("Lawyers")

    def __str__(self):
        return self.name

    def clean(self):
        """Digits only for fields `cpf` and `phone_number`"""
        if self.cpf:
            self.cpf = re.sub('[^0-9]', '', self.cpf)
        if self.phone_number:
            self.phone_number = re.sub('[^0-9]', '', self.phone_number)


class Proposal(models.Model):
    quotation = models.ForeignKey(
        verbose_name=_("Quotation"),
        to='company.Quotation',
        related_name='proposals'
    )
    lawyer = models.ForeignKey(
        verbose_name=_("Lawyer"),
        to=Lawyer,
        related_name='proposals'
    )
    price = models.DecimalField(
        verbose_name=_("Price"),
        max_digits=15,
        decimal_places=2
    )
    created_date = models.DateTimeField(
        verbose_name=_("Created date"),
        auto_now_add=True,
        editable=False
    )

    class Meta:
        verbose_name = _("Proposal")
        verbose_name_plural = _("Proposals")
        unique_together = ['quotation', 'lawyer']
        ordering = ['created_date']

    def __str__(self):
        return "PROP-{:05d}".format(self.pk)

lawyer/forms.py
from django import forms
from .models import Lawyer
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.models import User


class LawyerCreationForm(forms.ModelForm):
    """
    A form that creates a lawyer and related user with no privileges, from the given
    email and password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'user_exists': _("A user with that email already exists.")
    }
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = Lawyer
        exclude = ['user']

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_exists = User.objects.filter(username=email).exists()
        if user_exists:
            raise forms.ValidationError(
                self.error_messages['user_exists'],
                code='user_exists',
            )
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(password1)
        return password2

    def save(self, commit=True):
        lawyer = super(LawyerCreationForm, self).save(commit=False)
        if commit:
            user = User.objects.create_user(
                username=self.cleaned_data.get("email"),
                email=self.cleaned_data.get("email"),
                password=self.cleaned_data.get("password1"),
                first_name=self.cleaned_data.get("name")
            )
            lawyer.user = user
            lawyer.save()
        return lawyer

lawyer/views.py
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.utils.translation import ugettext_lazy as _
from utils.decorators import user_lawyer_required
from utils.paginator import listing
from .forms import LawyerCreationForm


def createaccount(request):
    if request.method == 'POST':
        form = LawyerCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _('Account created successfully'))
            return HttpResponseRedirect(reverse('login'))
    else:
        form = LawyerCreationForm()

    ctx = {
        'title': _("Create Account"),
        'form': form
    }
    return render(
        request,
        'lawyer/create-account.html',
        ctx
    )


@user_lawyer_required
def proposals(request):
    lawyer = request.user.lawyer
    ctx = {
        'proposals': listing(request, lawyer.proposals.all(), 10),
        'title': _('Proposals')
    }
    return render(
        request,
        'lawyer/proposals.html',
        ctx
    )

lawyer/templates/lawyer/create-account.html
{% extends 'website/base.html' %}
{% load static i18n bootstrap3 %}

{% block class_main %}
    class="main relative bg-img bg-cover overlay bg-color heavy"
    data-background="{% static 'website/images/banner/bg-03.jpg' %}" data-stellar-background-ratio="0.5"
{% endblock %}

{% block main %}
<div class="page-default typo-dark">
		<!-- Container -->
		<div class="container">
			<!-- Row -->
			<div class="row">
				<div class="col-md-offset-1 col-md-10 parent-has-overlay">
					<ul class="template-box box-login">
						<!-- Page Template Logo -->
						<li class="logo-wrap  text-center">
                            <h4 class="slogan">{% trans 'Create Account' %}</h4>
                            {% bootstrap_form_errors form error_types='all' %}
						</li><!-- Page Template Logo -->
						<!-- Page Template Content -->
						<li class="template-content text-left">
							<div class="contact-form">
								<!-- Form Begins -->
								<form name="bootstrap-form" method="post" action="{% url 'lawyer:create_account' %}">
									{% csrf_token %}
                                    <div class="row">
                                        {% bootstrap_field form.name form_group_class="input-text form-group col-md-6" %}
                                        {% bootstrap_field form.email form_group_class="input-text form-group col-md-6" %}
                                    </div>
                                    <div class="row">
                                        {% bootstrap_field form.phone_number form_group_class="input-text form-group col-md-6" %}
                                        {% bootstrap_field form.cpf form_group_class="input-text form-group col-md-6" %}
                                    </div>
                                    <div class="row">
                                        {% bootstrap_field form.password1 form_group_class="input-text form-group col-md-6" %}
                                        {% bootstrap_field form.password2 form_group_class="input-text form-group col-md-6" %}
                                    </div>
                                    <div class="row">
                                        <button class="btn btn-block  btn-success" type="submit">{% trans 'Create my account' %}</button>
                                        <p>or <a href="{% url 'login' %}">{% trans 'click here' %}</a> to login</p>
                                    </div>
								</form><!-- Form Ends -->
							</div>
						</li><!-- Page Template Content -->
					</ul>
				</div><!-- Column -->
			</div><!-- Row -->
		</div><!-- Container -->
	</div>
{% endblock %}

lawyer/templates/lawyer/proposals.html
{% extends 'website/base.html' %}
{% load static i18n bootstrap3 %}
{% block header %}
    <div class="page-header sm">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Page Header Wrapper -->
                    <div class="page-header-wrapper">
                        <!-- Title & Sub Title -->
                        <h5 class="title">{{ title }}</h5>
                    </div><!-- Page Header Wrapper -->
                </div><!-- Coloumn -->
            </div><!-- Row -->
        </div><!-- Container -->
    </div>
{% endblock %}
{% block main %}
    <section class="bg-grey pad-tb-30">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-md-9 parent-has-overlay">
					<table class="table table-hover">
						<thead>
							<tr>
								<th>#</th>
								<th class="text-center">{% trans 'Proposal date' %}</th>
								<th class="text-center">{% trans 'Quotation date' %}</th>
								<th>{% trans 'Quotation' %}</th>
								<th class="text-center">{% trans 'Quotation state' %}</th>
								<th class="text-center">{% trans 'Delegate' %}</th>
							</tr>
						</thead>
						<tbody>
                            {% for proposal in proposals %}
							<tr>
								<th scope="row">
                                    {{ proposal }}
                                </th>
								<td class="text-center">{{ proposal.created_date|date:"SHORT_DATE_FORMAT" }}</td>
								<td class="text-center">{{ proposal.quotation.created_date|date:"SHORT_DATE_FORMAT" }}</td>
								<td><a href="{% url 'website:quotation' proposal.quotation.pk %}">{{ proposal.quotation }}</a> </td>
								<td class="text-center"><span class="label label-{{ proposal.quotation.state_color }}">{{ proposal.quotation.get_state_display }}</span></td>
                                <td class="text-center">
                                    {% if proposal.quotation.delegated_to == proposal %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        {% if proposal.quotation.state == 'created' %}
                                            <i class="fa fa-clock-o text-primary"></i>
                                        {% else %}
                                            <i class="fa fa-remove text-danger"></i>
                                        {% endif %}
                                    {% endif %}
                                </td>

							</tr>
                        {% endfor %}
						</tbody>
					</table>
				</div>
            </div>
            <nav class="text-center">
                {% bootstrap_pagination proposals %}
            </nav>
        </div>
    </section>
{% endblock %}